export type StandardEmoji = { char: string; name: string; category: string; keywords: string };

export const STANDARD_EMOJI: StandardEmoji[] = [
  { char: '😀', name: 'grinning', category: 'Smileys', keywords: 'smile happy' },
  { char: '😃', name: 'smiley', category: 'Smileys', keywords: 'smile happy joy' },
  { char: '😄', name: 'smile', category: 'Smileys', keywords: 'smile happy laugh' },
  { char: '😁', name: 'grin', category: 'Smileys', keywords: 'grin happy' },
  { char: '😆', name: 'laughing', category: 'Smileys', keywords: 'laugh haha' },
  { char: '😅', name: 'sweat_smile', category: 'Smileys', keywords: 'sweat smile' },
  { char: '🤣', name: 'rofl', category: 'Smileys', keywords: 'rofl laugh hard' },
  { char: '😂', name: 'joy', category: 'Smileys', keywords: 'tears laugh cry' },
  { char: '🙂', name: 'slight_smile', category: 'Smileys', keywords: 'slight smile' },
  { char: '🙃', name: 'upside_down', category: 'Smileys', keywords: 'upside down' },
  { char: '😉', name: 'wink', category: 'Smileys', keywords: 'wink' },
  { char: '😊', name: 'blush', category: 'Smileys', keywords: 'blush smile' },
  { char: '😇', name: 'innocent', category: 'Smileys', keywords: 'innocent halo' },
  { char: '😍', name: 'heart_eyes', category: 'Smileys', keywords: 'love heart eyes' },
  { char: '🤩', name: 'star_struck', category: 'Smileys', keywords: 'stars eyes amazed' },
  { char: '😘', name: 'kiss', category: 'Smileys', keywords: 'kiss heart' },
  { char: '😗', name: 'kissing', category: 'Smileys', keywords: 'kiss' },
  { char: '🤔', name: 'thinking', category: 'Smileys', keywords: 'think hmm' },
  { char: '🤨', name: 'raised_brow', category: 'Smileys', keywords: 'eyebrow' },
  { char: '😐', name: 'neutral', category: 'Smileys', keywords: 'meh' },
  { char: '😑', name: 'expressionless', category: 'Smileys', keywords: 'flat' },
  { char: '😶', name: 'no_mouth', category: 'Smileys', keywords: 'silent' },
  { char: '🙄', name: 'eyeroll', category: 'Smileys', keywords: 'roll eyes' },
  { char: '😏', name: 'smirk', category: 'Smileys', keywords: 'smirk' },
  { char: '😒', name: 'unamused', category: 'Smileys', keywords: 'meh annoyed' },
  { char: '😞', name: 'disappointed', category: 'Smileys', keywords: 'sad' },
  { char: '😔', name: 'pensive', category: 'Smileys', keywords: 'sad' },
  { char: '😟', name: 'worried', category: 'Smileys', keywords: 'worry sad' },
  { char: '😕', name: 'confused', category: 'Smileys', keywords: 'confused' },
  { char: '🙁', name: 'slight_frown', category: 'Smileys', keywords: 'sad frown' },
  { char: '☹️', name: 'frown', category: 'Smileys', keywords: 'sad frown' },
  { char: '😣', name: 'persevere', category: 'Smileys', keywords: 'try' },
  { char: '😖', name: 'confounded', category: 'Smileys', keywords: 'confounded' },
  { char: '😫', name: 'tired', category: 'Smileys', keywords: 'tired' },
  { char: '😩', name: 'weary', category: 'Smileys', keywords: 'weary' },
  { char: '🥺', name: 'pleading', category: 'Smileys', keywords: 'plead beg' },
  { char: '😢', name: 'cry', category: 'Smileys', keywords: 'tear sad' },
  { char: '😭', name: 'sob', category: 'Smileys', keywords: 'sob cry' },
  { char: '😡', name: 'angry', category: 'Smileys', keywords: 'angry mad' },
  { char: '🤬', name: 'cursing', category: 'Smileys', keywords: 'curse mad' },
  { char: '🥳', name: 'party', category: 'Smileys', keywords: 'party celebrate' },
  { char: '😎', name: 'cool', category: 'Smileys', keywords: 'sunglasses cool' },
  { char: '🤓', name: 'nerd', category: 'Smileys', keywords: 'nerd glasses' },
  { char: '🥶', name: 'cold', category: 'Smileys', keywords: 'cold freeze' },
  { char: '🥵', name: 'hot', category: 'Smileys', keywords: 'hot heat' },
  { char: '😱', name: 'scream', category: 'Smileys', keywords: 'scream shock' },
  { char: '🤯', name: 'mind_blown', category: 'Smileys', keywords: 'mind blown' },
  { char: '👍', name: 'thumbsup', category: 'People', keywords: 'thumbs up like' },
  { char: '👎', name: 'thumbsdown', category: 'People', keywords: 'thumbs down dislike' },
  { char: '👏', name: 'clap', category: 'People', keywords: 'clap applause' },
  { char: '🙌', name: 'raised_hands', category: 'People', keywords: 'praise hooray' },
  { char: '👌', name: 'ok_hand', category: 'People', keywords: 'ok hand' },
  { char: '✌️', name: 'peace', category: 'People', keywords: 'peace' },
  { char: '🤞', name: 'crossed_fingers', category: 'People', keywords: 'crossed fingers luck' },
  { char: '🤟', name: 'love_you', category: 'People', keywords: 'love you' },
  { char: '🤘', name: 'rock_on', category: 'People', keywords: 'rock metal' },
  { char: '👋', name: 'wave', category: 'People', keywords: 'wave hi bye' },
  { char: '🤚', name: 'raised_back_hand', category: 'People', keywords: 'high five' },
  { char: '✋', name: 'raised_hand', category: 'People', keywords: 'high five stop' },
  { char: '👀', name: 'eyes', category: 'People', keywords: 'eyes look' },
  { char: '🫡', name: 'salute', category: 'People', keywords: 'salute' },
  { char: '🙏', name: 'pray', category: 'People', keywords: 'pray thanks' },
  { char: '💪', name: 'muscle', category: 'People', keywords: 'flex strong' },
  { char: '❤️', name: 'heart', category: 'Symbols', keywords: 'love heart red' },
  { char: '🧡', name: 'orange_heart', category: 'Symbols', keywords: 'orange heart' },
  { char: '💛', name: 'yellow_heart', category: 'Symbols', keywords: 'yellow heart' },
  { char: '💚', name: 'green_heart', category: 'Symbols', keywords: 'green heart' },
  { char: '💙', name: 'blue_heart', category: 'Symbols', keywords: 'blue heart' },
  { char: '💜', name: 'purple_heart', category: 'Symbols', keywords: 'purple heart' },
  { char: '🖤', name: 'black_heart', category: 'Symbols', keywords: 'black heart' },
  { char: '🤍', name: 'white_heart', category: 'Symbols', keywords: 'white heart' },
  { char: '💔', name: 'broken_heart', category: 'Symbols', keywords: 'broken heart' },
  { char: '💯', name: 'hundred', category: 'Symbols', keywords: '100 perfect' },
  { char: '🔥', name: 'fire', category: 'Symbols', keywords: 'fire lit' },
  { char: '⭐', name: 'star', category: 'Symbols', keywords: 'star' },
  { char: '✨', name: 'sparkles', category: 'Symbols', keywords: 'sparkles shine' },
  { char: '⚡', name: 'lightning', category: 'Symbols', keywords: 'zap lightning' },
  { char: '☀️', name: 'sun', category: 'Symbols', keywords: 'sun' },
  { char: '🌙', name: 'moon', category: 'Symbols', keywords: 'moon night' },
  { char: '⚠️', name: 'warning', category: 'Symbols', keywords: 'warning' },
  { char: '✅', name: 'check', category: 'Symbols', keywords: 'check ok done' },
  { char: '❌', name: 'cross', category: 'Symbols', keywords: 'no cross x' },
  { char: '❓', name: 'question', category: 'Symbols', keywords: 'question' },
  { char: '❗', name: 'exclamation', category: 'Symbols', keywords: 'exclaim' },
  { char: '🎉', name: 'party_popper', category: 'Symbols', keywords: 'celebrate party' },
  { char: '🎊', name: 'confetti', category: 'Symbols', keywords: 'confetti party' },
  { char: '🚀', name: 'rocket', category: 'Travel', keywords: 'rocket launch' },
  { char: '🐱', name: 'cat', category: 'Animals', keywords: 'cat kitten' },
  { char: '🐶', name: 'dog', category: 'Animals', keywords: 'dog puppy' },
  { char: '🦊', name: 'fox', category: 'Animals', keywords: 'fox' },
  { char: '🐼', name: 'panda', category: 'Animals', keywords: 'panda' },
  { char: '🐸', name: 'frog', category: 'Animals', keywords: 'frog' },
  { char: '🦀', name: 'crab', category: 'Animals', keywords: 'crab' },
  { char: '🍕', name: 'pizza', category: 'Food', keywords: 'pizza food' },
  { char: '🍔', name: 'burger', category: 'Food', keywords: 'burger food' },
  { char: '🍣', name: 'sushi', category: 'Food', keywords: 'sushi food' },
  { char: '🍺', name: 'beer', category: 'Food', keywords: 'beer drink' },
  { char: '🍷', name: 'wine', category: 'Food', keywords: 'wine drink' },
  { char: '☕', name: 'coffee', category: 'Food', keywords: 'coffee drink' },
];

export const EMOJI_CATEGORIES = ['Smileys', 'People', 'Animals', 'Food', 'Travel', 'Symbols'] as const;
